yarnPath: .yarn/releases/yarn-4.9.2.cjs

packageExtensions:
  '@aws-crypto/kms-keyring-node@^4.2.1':
    dependencies:
      '@aws-crypto/material-management': '*'
  '@aws-crypto/branch-keystore-node@^4.2.1':
    dependencies:
      '@aws-crypto/material-management': '*'
      '@aws-sdk/client-kms': '*'
      uuid: '^10.0.0'
  '@aws-crypto/kdf-ctr-mode-node@^4.1.0':
    dependencies:
      '@aws-crypto/material-management': '*'
      '@aws-crypto/serialize': '*'
  eslint-module-utils@^2.12.1:
    dependencies:
      '@typescript-eslint/parser': '*'
